# Generated by Django 5.1 on 2024-09-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.CharField(choices=[('ALUNO', 'aluno'), ('PROFESSOR', 'professor')], default='ALUNO', max_length=10, verbose_name='tipo pessoa'),
        ),
    ]
