# Generated by Django 5.1 on 2024-09-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_pessoa_tipo_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('num', models.DecimalField(decimal_places=0, max_digits=5)),
                ('complemento', models.TextField(max_length=8)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.CharField(choices=[('ALUNO', 'aluno'), ('PROFESSOR', 'professor')], default='ALUNO', max_length=10, verbose_name='tipo de pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='pessoa.endereco'),
        ),
    ]
