# Generated by Django 5.0.4 on 2024-08-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='path_to_save_pdfs/')),
                ('ata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='ata.atas')),
            ],
        ),
    ]
