# Generated by Django 5.1 on 2024-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atas',
            name='serie',
            field=models.CharField(choices=[('1', '1º ano'), ('2', '2º ano'), ('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano')], max_length=50),
        ),
        migrations.AlterField(
            model_name='atas',
            name='turma',
            field=models.CharField(choices=[('A', 'Turma A'), ('B', 'Turma B'), ('C', 'Turma C'), ('D', 'Turma D'), ('E', 'Turma E'), ('F', 'Turma F')], max_length=50),
        ),
    ]
