# Generated by Django 5.0.4 on 2024-08-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0002_arquivopdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivopdf',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='arquivopdf',
            name='ata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ata.atas'),
        ),
        migrations.AlterField(
            model_name='arquivopdf',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
